export default {
    mfRatesTable : [
        { name: 'District Id', selector: 'districtId', width: '120px' },
        { name: 'District Name', selector: 'districtName', width: '220px' },
        {
          name: 'Facility Id',
          selector: 'facilityId',
          width: '120px',
        },
        { name: 'Facility Name', selector: 'facilityName', width: '250px' },
        { name: 'MF Rate', selector: 'mfRate', width: '120px' },
        { name: 'Month', selector: 'month', width: '120px' },
        { name: 'Name of Control Unit', selector: 'nameOfControlUnit', width: '200px' },
        { name: 'Name of Unit Id', selector: 'nameOfUnitId', width: '220px' },
        {
          name: 'No of Persions Examined',
          selector: 'noOfPersonsExamined',
          width: '220px',
        },
        { name: 'No of Persions MF Positive', selector: 'noOfPersonsMFPositive', width: '220px' },
        { name: 'Village Id', selector: 'villageId', width: '120px' },
        { name: 'Village Name', selector: 'villageName', width: '250px' },
        { name: 'Year', selector: 'year', width: '120px' },
      ],
      LFTable : [
        { name: 'Age (Years)', selector: 'ageYears', width: '120px' },
        { name: 'District Id', selector: 'districtId', width: '120px' },
        { name: 'District Name', selector: 'districtName', width: '220px' },
        {
          name: 'Facility Id',
          selector: 'facilityId',
          width: '120px',
        },
        { name: 'Facility Name', selector: 'facilityName', width: '250px' },
        { name: 'Gender', selector: 'gender', width: '120px' },
        { name: 'Grading', selector: 'grading', width: '120px' },
        { name: 'Month', selector: 'month', width: '120px' },
        { name: 'Name of Patient', selector: 'nameOfPatient', width: '200px' },
        { name: 'Name of Patient Id', selector: 'nameOfPatientId', width: '180px' },
        {
          name: 'Patient Mobile Number',
          selector: 'patientMobileNumber',
          width: '180px',
        },
        { name: 'Village Id', selector: 'villageId', width: '120px' },
        { name: 'Village Name', selector: 'villageName', width: '250px' },
        { name: 'Year', selector: 'year', width: '120px' },
      ],
      Alerts : [
        { name: 'User Name', selector: 'userName', width: '120px' },
        { name: 'Designation', selector: 'designation', width: '120px' },
        { name: 'Email', selector: 'email', width: '220px' },
        {
          name: 'Mobile No',
          selector: 'mobileNumber',
          width: '150px',
        },
        { name: 'Email Triggerd', selector: 'isTriggerEmail', width: '120px' },
        { name: 'Email Text', selector: 'textEmail', width: '220px' },
        { name: 'SMS Triggered', selector: 'isTriggerSMS', width: '120px' },
        { name: 'SMS Text', selector: 'textSMS', width: '220px' },
        { name: 'Trigger Name', selector: 'triggerName', width: '200px' },
        { name: 'Created on', selector: 'createdAt', width: '180px' }
      ]
}