export const MDA_TAS_Data = [
  {
    "Name of District": "Akola",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "22-Jul-14",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "3-5 Jan 2017",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "25 Feb- 1 Mar 2019",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Jalgaon",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "2-Apr-14",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "10-12 Jan 2017",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "25 Feb- 1 Mar 2019",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Sindhudurg",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "5-Apr-14",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "10-12 Jan 2017",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "25 Feb- 1 Mar 2019",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Solapur",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "19-23 Dec 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "27 Dec 2017 to 1 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "15-20 Jan 20",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Wardha",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "3-5 March 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "18 Dec 2017 to 4 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "15-20 Jan 20",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Osmanabad",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "26 Dec 2017 to 1 Jan 2018",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "18 to 22 Nov 2019",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 Sep to 2 Oct 2021",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Yavatmal West-EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "3-5 March 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "8 Jan-12 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 to 31 Jan 2020",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Yavatmal East-EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "3-5 March 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "8 Jan-12 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 to 31 Jan 2020",
    "TAS 3 Outcome": "Fail",
  },
  {
    "Name of District": "Amrawati East-EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "3-8 Mar 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "8 Jan-12 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 to 31 Jan 2020",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Amrawati West-EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "3-8 Mar 2015",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "8 Jan-12 Jan 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 to 31 Jan 2020",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Latur- EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "13-15 Jan 2017",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "25 Feb to 1 Mar 2019",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 Sep to 2 Oct 2021",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Latur-Nilanga EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "14-15 Jan 2017",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "26 Feb to 1 Mar 2019",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "27 Sep to 2 Oct 2021",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Nandurbar",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "11-13 Nov 2017",
    "TAS 1 Outcome": "Fail",
  },
  {
    "Reported Coverage of all MDA rounds": "R6-        R7-",
    "TAS 1 in year": "19-23 March 18",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "27-30 Sept 2021",
    "TAS 2 Outcome": "Fail. Repeat TAS 1 After 2 MDA round",
  },
  {
    "Name of District": "Thane-Shahpur EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-10 Oct 2016",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "3-7 Dec 2018",
    "TAS 2 Outcome": "Pass",
    "TAS 3 in year": "4-7 Oct 2021",
    "TAS 3 Outcome": "Pass",
  },
  {
    "Name of District": "Thane- Kalyan EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Thane Bhiwandi EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in Oct 2023) After 2 MDA round",
  },
  {
    "Name of District": "Palghar EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Palghar Vasai 1 EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Palghar Vasai 2 EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Palghar-Dahanu EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "4-7 Oct 2021",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in Oct 2023) After 2 MDA round",
  },
  {
    "Name of District": "Nagpur- Katol EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "27 Sep - 4 Oct 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Nagpur- Umred EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "27 Sep - 4 Oct 2021",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in Oct 2023) After 2 MDA round",
  },
  {
    "Name of District": "Nagpur-Medical EU",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "27 Sep - 4 Oct 2021",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in Oct 2023) After 2 MDA round",
  },
  {
    "Name of District": "Nagpur-Mayo",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "27 -30 Sep 2021",
    "TAS 1 Outcome": "Pass",
    "TAS 2 in year": "Proposed in Oct 2023",
    "TAS 3 in year": "Proposed in Oct 2025",
  },
  {
    "Name of District": "Bhandara",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "16 -21 Dec 2019",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in 2022) After 2 MDA round",
    "TAS 2 in year": "Proposed in March 2024",
    "TAS 3 in year": "Proposed in March 2026",
  },
  {
    "Name of District": "Gondia",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "Aug - Sep 2019",
    "TAS 1 Outcome": "Fail. Repeat TAS 1 (in 2022) After 2 MDA round",
    "TAS 2 in year": "Proposed in March 2024",
    "TAS 3 in year": "Proposed in March 2026",
  },
  {
    "Name of District": "Chandrapur",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "Proposed in March 2022",
    "TAS 2 in year": "Proposed in March 2024",
    "TAS 3 in year": "Proposed in March 2026",
  },
  {
    "Name of District": "Gadchiroli",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "Proposed in March 2022",
    "TAS 2 in year": "Proposed in March 2024",
    "TAS 3 in year": "Proposed in March 2026",
  },
  {
    "Name of District": "Nanded",
    "Reported Coverage of all MDA rounds":
      "R1-       R2-     R3-       R4-      R5-   ",
    "TAS 1 in year": "Proposed in March 2022",
    "TAS 2 in year": "Proposed in March 2024",
    "TAS 3 in year": "Proposed in March 2026",
  },
];

export const FCUData = [
  {
    District: "Yavatmal",
    "FCU Name": "92",
    "Target ": "90",
    Achieved: "92",
    "Achieved %": "90",
  },
  {
    District: "Nandurbar",
    "FCU Name": "88",
    "Target ": "85",
    Achieved: "88",
    "Achieved %": "85",
  },
  {
    District: "Thane",
    "FCU Name": "93.99",
    "Target ": "86.5",
    Achieved: "93.99",
    "Achieved %": "86.5",
  },
  {
    District: "Palghar",
    "FCU Name": "94",
    "Target ": "91",
    Achieved: "94",
    "Achieved %": "91",
  },
  {
    District: "Nagpur",
    "FCU Name": "84.59",
    "Target ": "76.4",
    Achieved: "84.59",
    "Achieved %": "76.4",
  },
  {
    District: "Bhandara",
    "FCU Name": "89.7",
    "Target ": "71.24",
    Achieved: "89.7",
    "Achieved %": "71.24",
  },
  {
    District: "Gondia",
    "FCU Name": "93.4",
    "Target ": "83.5",
    Achieved: "93.4",
    "Achieved %": "83.5",
  },
  {
    District: "Chandrapur",
    "FCU Name": "91.41",
    "Target ": "74.72",
    Achieved: "91.41",
    "Achieved %": "74.72",
  },
  {
    District: "Gadchiroli",
    "FCU Name": "92.6",
    "Target ": "92.6",
    Achieved: "92.6",
    "Achieved %": "92.6",
  },
  {
    District: "Nanded",
    "FCU Name": "91.7",
    "Target ": "97.38",
    Achieved: "91.7",
    "Achieved %": "97.38",
  },
];

export const FSU_Data = [
  {
    unitName: "Pune",
    PETarget: "36000",
    PEAch: "1302",
    "PE%Ach": "3.62",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
    // "PETargetTot": "216000",
    // "PEAchTot": "45396",
    // "PE%AchTot": "21.02",
    // "FCMfTot": "3",
    // "FCDisTot": "17",
    // "FCTotalTot": "20",
    // "FCTMfTot": "3",
    // "FCTDisTot": "17",
    // "FCTTotalTot": "20",
  },
  {
    unitName: "Thane ",
    PETarget: "36000",
    PEAch: "4024",
    "PE%Ach": "11.18",
    FCMf: "2",
    FCDis: "1",
    FCTotal: "3",
    FCTMf: "2",
    FCTDis: "1",
    FCTTotal: "3",
  },
  {
    unitName: "Nagpur ",
    PETarget: "36000",
    PEAch: "16416",
    "PE%Ach": "45.60",
    FCMf: "1",
    FCDis: "8",
    FCTotal: "9",
    FCTMf: "1",
    FCTDis: "8",
    FCTTotal: "9",
  },
  {
    unitName: "Aurangabad ",
    PETarget: "36000",
    PEAch: "6706",
    "PE%Ach": "18.63",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "Nasik",
    PETarget: "36000",
    PEAch: "6459",
    "PE%Ach": "17.94",
    FCMf: "0",
    FCDis: "1",
    FCTotal: "1",
    FCTMf: "0",
    FCTDis: "1",
    FCTTotal: "1",
  },
  {
    unitName: "Akola",
    PETarget: "36000",
    PEAch: "10489",
    "PE%Ach": "29.14",
    FCMf: "0",
    FCDis: "7",
    FCTotal: "7",
    FCTMf: "0",
    FCTDis: "7",
    FCTTotal: "7",
  },
];

export const FCU_Data = [
  {
    unitName: "Vasai",
    PETarget: "21600",
    PEAch: "7834",
    "PE%Ach": "36.26851852",
    FCMf: "1",
    FCDis: "0",
    FCTotal: "1",
    FCTMf: "1",
    FCTDis: "0",
    FCTTotal: "1",
  },
  {
    unitName: "Palghar",
    PETarget: "7200",
    PEAch: "3304",
    "PE%Ach": "45.88888889",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "Akkalkot",
    PETarget: "28800",
    PEAch: "4808",
    "PE%Ach": "16.69444444",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "Nanded",
    PETarget: "57600",
    PEAch: "43438",
    "PE%Ach": "75.41319444",
    FCMf: "5",
    FCDis: "6",
    FCTotal: "11",
    FCTMf: "5",
    FCTDis: "6",
    FCTTotal: "11",
  },
  {
    unitName: "Amravati",
    PETarget: "72000",
    PEAch: "49321",
    "PE%Ach": "68.50138889",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "Bhandara",
    PETarget: "43200",
    PEAch: "14096",
    "PE%Ach": "32.62962963",
    FCMf: "2",
    FCDis: "54",
    FCTotal: "56",
    FCTMf: "2",
    FCTDis: "54",
    FCTTotal: "56",
  },
  {
    unitName: "Pawani",
    PETarget: "7200",
    PEAch: "4241",
    "PE%Ach": "58.90277778",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "Chandrapur",
    PETarget: "64800",
    PEAch: "29443",
    "PE%Ach": "45.4367284",
    FCMf: "78",
    FCDis: "0",
    FCTotal: "78",
    FCTMf: "78",
    FCTDis: "0",
    FCTTotal: "78",
  },
  {
    unitName: "Rajura",
    PETarget: "31200",
    PEAch: "18821",
    "PE%Ach": "60.32371795",
    FCMf: "2",
    FCDis: "0",
    FCTotal: "2",
    FCTMf: "2",
    FCTDis: "0",
    FCTTotal: "2",
  },
  {
    unitName: "Gadchiroli",
    PETarget: "43200",
    PEAch: "25819",
    "PE%Ach": "59.7662037",
    FCMf: "104",
    FCDis: "1",
    FCTotal: "105",
    FCTMf: "104",
    FCTDis: "1",
    FCTTotal: "105",
  },
  {
    unitName: "Dhanora",
    PETarget: "36000",
    PEAch: "14582",
    "PE%Ach": "40.50555556",
    FCMf: "4",
    FCDis: "0",
    FCTotal: "4",
    FCTMf: "4",
    FCTDis: "0",
    FCTTotal: "4",
  },
  {
    unitName: "Nagpur",
    PETarget: "64800",
    PEAch: "36883",
    "PE%Ach": "56.91820988",
    FCMf: "3",
    FCDis: "0",
    FCTotal: "3",
    FCTMf: "3",
    FCTDis: "0",
    FCTTotal: "3",
  },
  {
    unitName: "Umred",
    PETarget: "7200",
    PEAch: "3868",
    "PE%Ach": "53.72222222",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "R.C.T.C. Nagpur",
    PETarget: "9600",
    PEAch: "4541",
    "PE%Ach": "47.30208333",
    FCMf: "1",
    FCDis: "0",
    FCTotal: "1",
    FCTMf: "1",
    FCTDis: "0",
    FCTTotal: "1",
  },
  {
    unitName: "Wardha",
    PETarget: "36000",
    PEAch: "14294",
    "PE%Ach": "39.70555556",
    FCMf: "0",
    FCDis: "0",
    FCTotal: "0",
    FCTMf: "0",
    FCTDis: "0",
    FCTTotal: "0",
  },
  {
    unitName: "T.M.C.",
    PETarget: "21600",
    PEAch: "6763",
    "PE%Ach": "31.31018519",
    FCMf: "0",
    FCDis: "1",
    FCTotal: "1",
    FCTMf: "0",
    FCTDis: "1",
    FCTTotal: "1",
  },
  {
    unitName: "N.M.C.",
    PETarget: "86400",
    PEAch: "13828",
    "PE%Ach": "16.00462963",
    FCMf: "0",
    FCDis: "28",
    FCTotal: "28",
    FCTMf: "0",
    FCTDis: "28",
    FCTTotal: "28",
  },
];
